'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SummaryDisplayMode

    Partial Public Class DefaultForm

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''rgSummaryDisplayTypeGroups control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rgSummaryDisplayTypeGroups As Global.DevExpress.Web.ASPxRadioButtonList

        '''<summary>
        '''ddlSummaryDisplayType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSummaryDisplayType As Global.DevExpress.Web.ASPxComboBox

        '''<summary>
        '''cbShowRawValues control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbShowRawValues As Global.DevExpress.Web.ASPxCheckBox

        '''<summary>
        '''cbAllowCrossGroupVariation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbAllowCrossGroupVariation As Global.DevExpress.Web.ASPxCheckBox

        '''<summary>
        '''pivotGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pivotGrid As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid

        '''<summary>
        '''cachedSourceDataFieldName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cachedSourceDataFieldName As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''ProductReportsDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProductReportsDataSource As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''SalesPersonsDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SalesPersonsDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    End Class
End Namespace
